language: python

python:
  - "3.6"
  - "3.7"

after_success:
- coveralls

script:
  - travis_wait 40 bash travis/install_test_linux.sh

##
#stages:
#  - test
#  # Only execute deployment stage on tagged commits, and from your repository
#  # (e.g. not PRs). Replace with your repo name.
#  - deploy
##  - name: deploy
##    if: tag IS PRESENT AND repo = joerick/cibuildwheel
##    if: repo = adamltyson/cellfinder

#stages:
#  - test
#  - name: deploy
#    if:
##      tag IS present AND repo = adamltyson/cellfinder
#      repo = adamltyson/cellfinder
##      - branch = deploy
##      - tag IS present


jobs:
  include:
    - stage: deploy
      on:
        branch: deploy
        tags: true
        repo: adamltyson/cellfinder
      services:
        - docker
      script:
        - pip install twine
        - mkdir pypi_upload
        - python setup.py sdist
        - cp dist/* pypi_upload/
#        - docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2010_x86_64 /io/travis/build_linux_wheels.sh
#        - cp wheelhouse/manylinux/* pypi_upload/
      after_success:
        - pip install twine
        - ls pypi_upload/*
        - twine upload pypi_upload/* --skip-existing

notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always


env:
  global:
    - TWINE_USERNAME=__token__
    # TWINE_PASSWORD is set to a PyPI API token in Travis settings