language: python

matrix:
  include:
  - os: linux
    python: 3.6
    dist: bionic
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='bash travis/install_test_linux.sh'
  - os: linux
    python: 3.7
    dist: bionic
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='bash travis/install_test_linux.sh'


after_success:
- coveralls

script:
  - travis_wait 40 $TEST_CMD

stages:
  - test
  - name: deploy
    if:
      tag IS present AND repo = adamltyson/cellfinder

jobs:
  include:
    - stage: deploy
      services:
        - docker
      script:
        - pip install twine
        - mkdir pypi_upload
        - python setup.py sdist
        - cp dist/* pypi_upload/
#        - docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2010_x86_64 /io/travis/build_linux_wheels.sh
#        - cp wheelhouse/manylinux/* pypi_upload/
      after_success:
        - pip install twine
        - ls pypi_upload/*
        - twine upload pypi_upload/* --skip-existing

notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always

env:
  global:
    - TWINE_USERNAME=__token__
    # TWINE_PASSWORD is set to a PyPI API token in Travis settings