language: python

python:
  - "3.6"
  - "3.7"

#matrix:
#  include:
#    - os: linux
#      python: 3.6
#      dist: bionic
#    - os: linux
#      python: 3.7
#      dist: bionic
#
#before_install:
#  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#  - bash miniconda.sh -b -p $HOME/miniconda
#  - export PATH="$HOME/miniconda/bin:$PATH"
#  - hash -r
#  - conda config --set always_yes yes --set changeps1 no
#  - conda info -a
#  -
#
#install:
#  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
#  - source activate test-environment
#  - pip install -e .[dev]
#  - conda info -a

after_success:
- coveralls
#- # maybe add deployment here

script:
  - travis_wait 40 bash travis/install_test_linux.sh

##
#stages:
#  - test
#  # Only execute deployment stage on tagged commits, and from your repository
#  # (e.g. not PRs). Replace with your repo name.
#  - deploy
##  - name: deploy
##    if: tag IS PRESENT AND repo = joerick/cibuildwheel
##    if: repo = adamltyson/cellfinder

stages:
  - test
  - name: deploy
    if:
      - repo = adamltyson/cellfinder AND branch = deploy


jobs:
  include:
    - stage: deploy
      sudo: required
      services:
        - docker
      script:
        - pip install twine
        - mkdir pypi_upload
        - python setup.py sdist
        - cp dist/* pypi_upload/
#        - docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2010_x86_64 /io/travis/build_wheels.sh
        - cp wheelhouse/manylinux/* pypi_upload/
      after_success:
        - pip install twine
        - ls pypi_upload/*
        - twine upload pypi_upload/* --skip-existing

notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always


env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings